//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dana
{
    using System;
    using System.Collections.Generic;
    
    public partial class uesr_
    {
        public int id { get; set; }
        public string Username { get; set; }
        public string Password_ { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Phone_number { get; set; }
        public string City { get; set; }
    }
}
